services:
  db:
    image: postgres:15-alpine
    container_name: lct_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin_password}
      POSTGRES_DB: ${POSTGRES_DB:-rtk_crm}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - lct_net

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    container_name: lct_keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-rtk_crm}
      KC_DB_USERNAME: ${POSTGRES_USER:-admin}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-admin_password}
      KEYCLOAK_ADMIN: ${KC_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD:-admin}
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - lct_net

  backend:
    build: .
    container_name: lct_fastapi
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin_password}@db:5432/${POSTGRES_DB:-rtk_crm}
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - lct_net

  minio:
    image: quay.io/minio/minio:latest
    container_name: lct_minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-admin_password}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - lct_net

volumes:
  pg_data:
  minio_data:

networks:
  lct_net:
    driver: bridge